# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13630d48035360b2fb1a95fdb8a22df3544102b36a11bf1a3a10b573c08ae391de011ad6e35b2972a5265cee3ff1806cc45154808bedb99d18f7e326a8af636c

test:
  secret_key_base: 1415e8854cc880f4128f5b6e8b294398a6efd482d57fae8f1327711fc7cdd34e8cd537bae921d7026e7c02bbac5c97b6907bdf66ef661025cb044b1d54ed94b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
